site_name: Eduardo Ocejo Vallin
nav:
  - Home: index.md
  - Experience: experience.md
  - Education: education.md
  - Writing Skills: skills-writing.md
  - Additional Skills: skills-other.md

theme:
  name: cinder
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png

extra_css:
- css/extra.css